name: Build boost

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Initialize
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Git clone
      run: |
        git clone https://github.com/boostorg/boost.git boost -b boost-1.81.0 --depth 1 --recursive

    - name: Build
      working-directory: ./boost
      run: |
        ./bootstrap.bat
        ./b2.exe install -j2 --prefix=../outputs/Debug --with-math variant=debug
        ./b2.exe install -j2 --prefix=../outputs/Release --with-math variant=release

    - name: The job has succeeded
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: boost
        path: boost/outputs
        
    # - name: Setup tmate session
    #   if: ${{ failure() }}
    #   uses: mxschmitt/action-tmate@v3
    #   timeout-minutes: 30
