name: Build tokenizer

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Initialize
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Git clone
      run: |
        git clone https://github.com/OpenNMT/Tokenizer.git tokenizer -b v1.37.1 --depth 1 --recursive

    - name: Build
      working-directory: ./tokenizer
      run: |
        bash ../tools/build_tokenizer.sh

    - name: The job has succeeded
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: tokenizer
        path: tokenizer/outputs
        
    # - name: Setup tmate session
    #   if: ${{ failure() }}
    #   uses: mxschmitt/action-tmate@v3
    #   timeout-minutes: 30
