name: Build translate

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Initialize
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Git clone
      run: |
        git clone https://github.com/OpenNMT/CTranslate2.git translate -b v3.7.0 --depth 1 --recursive

    - name: Build
      working-directory: ./translate
      run: |
        bash ../tools/build_translate.sh

    - name: The job has succeeded
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: translate
        path: translate/outputs
        
    # - name: Setup tmate session
    #   if: ${{ failure() }}
    #   uses: mxschmitt/action-tmate@v3
    #   timeout-minutes: 30
